In [25]:
import pandas as pd
import sqlalchemy as sal
engine=sal.create_engine("mssql+pyodbc://LAPTOP-MRKDUIFF\SQLEXPRESS01/master?driver=ODBC+DRIVER+17+FOR+SQL+SERVER")
conn=engine.connect()

In [20]:
import pandas as pd 
def extract():
    df_orders=pd.read_csv("orders.txt")
    df_returns=pd.read_csv("returns.txt")
    return df_orders,df_returns

In [23]:
def transform(orders,returns):
    df=pd.merge(orders,returns,how="inner",left_on="order_id",right_on="order_id")
    return df

In [36]:
#load
def load(df):
    df.to_sql("orders_final",con=conn,index=False,if_exists="replace")
    conn.commit()

In [37]:
#extract
df_orders,df_returns=extract()
#transform
df=transform(df_orders,df_returns)
#load
load(df)

In [ ]:
# read_sql_query

In [40]:
df=pd.read_sql_query("select * from orders_final",conn)
df

,order_id,order_date,customer_name,city,category,product_id,sales,profit,Return Reason
0,CA-2018-100762,2018-11-24,Nat Gilpin,Jackson,Office Supplies,OFF-AR-10000380,151.920,45.5760,Bad Quality
1,CA-2018-100867,2018-10-19,Eugene Hildebrand,Lakewood,Technology,TEC-PH-10004922,321.552,20.0970,Bad Quality
2,CA-2018-102652,2018-04-06,Andy Yotov,Los Angeles,Furniture,FUR-FU-10000747,91.960,15.6332,Bad Quality
3,CA-2018-103373,2018-05-18,Bruce Stewart,Cleveland,Technology,TEC-PH-10002885,779.796,-168.9558,Bad Quality
4,CA-2018-103744,2018-02-23,Michael Grace,El Paso,Office Supplies,OFF-BI-10000320,4.428,-6.8634,Bad Quality
...,...,...,...,...,...,...,...,...,...
291,US-2021-136679,2021-11-14,Xylona Preis,Pasadena,Office Supplies,OFF-AR-10003582,45.040,4.5040,Others
292,US-2021-147886,2021-03-28,Dave Hallsten,Fairfield,Furniture,FUR-FU-10001095,26.480,10.0624,Others
293,US-2021-147998,2021-05-19,Sue Ann Reed,San Jose,Office Supplies,OFF-BI-10002082,133.120,49.9200,Wrong Items
294,US-2021-151127,2021-05-22,Rob Lucas,Los Angeles,Office Supplies,OFF-AR-10002445,49.560,18.8328,Wrong Items
295,US-2021-155999,2021-08-07,Jay Kimmel,San Diego,Office Supplies,OFF-BI-10000404,13.760,4.6440,Wrong Items